#
# Simply build and test by https://travis-ci.org
#
language: java

jdk:
- oraclejdk8

before_install:
- chmod +x gradlew

#after_success:
#- ./gradlew jacocoTestReport coveralls

#cache:
# directories:
# - ~/.gradle/wrapper
# - ~/.gradle/caches
